### ISSUE TITLE
Missing property

### ISSUE THREAD

**Issue by AntonSkochko** [EugeneDyachenko/video-playground#1]
Looked over event listeners, noticed you've missed _previousRight property in component property list.

https://github.com/EugeneDyachenko/video-playground/blob/91d808a7cd79677624451f976b0105ba3f33dcf7/range-slider.html#L126

**Comment by EugeneDyachenko** [comment]
Thanks. Fixed in [**video-playground `73bc221`**](https://github.com/EugeneDyachenko/video-playground/commit/73bc2216ea95d0a0a1e0ed344dc504fbb81331be)
